region: us
version: '2'
authtoken: <your-auth-token>
tunnels:
  twilio-app:
    addr: twilio-app:8001
    proto: http
  plivo-app:
    addr: plivo-app:8002
    proto: http
  callagent-app:
    addr: callagent-app:5001
    proto: http